### PR TITLE
Add ethereum social support

### PR DESCRIPTION
**Pull request by akx20000a**
Ethereum Social (aka ETSC) is a community-oriented POW ethereum network.

+ EIP-155 enabled and Chain id 214.
+ Tested on https://wallet.ethereumsocial.kr
+ Trezor support tested in the ellawallet fork
+ More info on gazua.tv (kor) (eng will be supported soon)

### CODE REVIEW

**Comment by yograterol** [comment]
The node is slow

**Comment by ghost** [comment]
@yograterol It uses geth & nginx reverse proxy & located in korea 😂 How about callisto?

**Comment by Dexaran** [comment]
@akx20000a Callisto mainnet is not yet launched.
Callisto testnet is just a testnet.

**Comment by Dexaran** [comment]
@akx20000a I will ask you to release a web page of the Ethereum Social project so that I can read more about it and review the source codes.

We will be happy to add ETSC support at ClassicEtherWallet then.

**Comment by hackmod** [comment]
Ethereum Social Project != EtherSocial Project and the Ethereum Social is mere a hardfork of the real EtherSocial Coin.

EtherSocial Coin (ESC) | Ethereum Social Coin (ETSC)
------------------------|----------
https://ethersocial.org/eng/index.html | no homepage (http://ethereumsocial.kr/ )
White paper (in Korean now) : https://ethersocial.org/eng/index.html#whitepaper | no white paper
Community support (Since 2013~ most Popular blockchain/mining community in Korea) : https://www.ddengle.com | FIXME
Devs : @ethersocialcoin , @KIM-MYEONGHUN  | @akx20000a , @bitminings (owner of https://http://www.gazua.tv )
Source code release date (Jan 31, 2018) : https://github.com/ethersocial/go-esc (See also the attached image)  | a fork of the original ESC after their release date. (Feb 9, 2018)
Network Hash rate : ~100GH/s | ~1.5GH/s
not official pool sites : about ~5. https://en.escpool.com , https://esc.gonsmine.com/ https://esc.dreampool.info | only 1 (https://mineesc.com . not mine **"etsc"** dot com ) hardforked at this site.
network state (peer explorer) : https://escstats.gonsmine.com (not a official site) | https://stats.ethereumsocial.kr/
Feed back site : https://www.ddengle.com/esc_board | http://www.gazua.tv/post/ho

image

cross post at kvhnuke/etherwallet/pull/1610

See also BTCPrivate/BitcoinPrivate/issues/37 and @hsol's commnet

**Comment by ghost** [comment]
@hackmod Get lost, you are not a Ethereum Social developer nor "EtherSocial" developer
And I am not a related person of you call it "Bitcoin Platinum" or whatever 😄

**Comment by ghost** [comment]
White paper (in Korean now) :  That looks like a local ponzi or a pyramid scam to me

**Comment by ghost** [comment]
# SCAM WARNING: EtherSocial(ESC) is a ethereum based fork coin made by a HACKED cryptoexchange
## Youbit exchange bankruptcy

https://www.cnbc.com/2017/12/19/yapian-youbit-exchange-files-bankruptcy.html
https://news.bitcoin.com/korean-exchange-youbit-bankruptcy-members-options/
http://www.econonews.co.kr/news/articleView.html?idxno=15503
http://www.sporbiz.co.kr/news/articleView.html?idxno=183524

## Relationship between ddengle.com and youbit

http://biz.chosun.com/site/data/html_dir/2017/12/19/2017121902494.html
https://www.ddengle.com/board_free/4446196
https://www.ddengle.com/board_free/3651725
http://gall.dcinside.com/board/view/?id=bitcoins&no=4461654

## Conclusion

+ Youbit has been started as a "ddengle" exchange
+ They hacked twice, and there was no apology or refunds (Instead, they gave victims their company's stock)
+ They assumed that they are in "bankruptcy" mode, and now they are making a huge "ponzi" scam coin called ESC
+ They premined about 50% ESC of a total supply, now it is in danger of being hacked again.

## My opinion

I think ESC is the expansion package of "yam" scam Fin.

**Comment by hackmod** [comment]
@akx20000a poor young man... "the E**T**SC(Ethereum Social coin) is a hardfork of the ESC(EtherSocial Coin) blockchain" that's the most important fact.

**Comment by ghost** [comment]
@hackmod  Get lost, this is an open source community, and not a trading forum, though :)

**Comment by akx20000a** [comment]
@hackmod This is my final warning, besides you are saying

**Comment by ghost** [comment]
@hackmod 며칠 안 보이더니 근거 없는 자존심이 좀 회복되었나 보네요?
계속 young man 거리시는걸 보니 님은 old man 인가요?

**Comment by hackmod** [comment]
@akx20000a 앞날이 진심으로 걱정되어서 그래요. 정신좀 빨리 차리세요. 이는 매일 닦고 다닙니다.

**Comment by ghost** [comment]
.

**Comment by ghost** [comment]
@hackmod 논거 없는 주장 보니까 땡글 알바는 아닌듯하네요

**Comment by akx20000a** [comment]
EtherSocial Coin (ESC) | Ethereum Social Coin (ETSC)
-- | --
https://ethersocial.org/eng/index.html | no homepage (http://ethereumsocial.kr/ )
) : https://ethersocial.org/eng/index.html#whitepaper | no white paper
Community support (Since 2013~ most Popular blockchain/mining community in Korea) : https://www.ddengle.com | FIXME
Devs : @ethersocialcoin , @KIM-MYEONGHUN | @akx20000a , @bitminings (owner of https://http://www.gazua.tv )
Source code release date (Jan 31, 2018) : https://github.com/ethersocial/go-esc (See also the attached image) | a fork of the original ESC after their release date. (Feb 9, 2018)
Network Hash rate : ~100GH/s | ~1.5GH/s
not official pool sites : about ~5. https://en.escpool.com, https://esc.gonsmine.com/ https://esc.dreampool.info | only 1 (https://mineesc.com . not mine "etsc" dot com ) they are hardforked at this site.
network state (peer explorer) : https://escstats.gonsmine.com (not a official site) | https://stats.ethereumsocial.kr/
Feed back site : https://www.ddengle.com/esc_board | http://www.gazua.tv/post/ho

**Comment by hackmod** [comment]
@akx20000a Please came down and relax. your future is bright and promising, except this childish behavior.

**Comment by ghost** [comment]
.

**Comment by hackmod** [comment]
@akx20000a 제 전화번호 들어있는 이메일 보낸지가 3일이 넘었네요? 이메일은 구닥다리라서 읽지 않으시는지? 욕을 바가지로 저에게 하시더라도 들을 준비 되어있으니 하시길 바랍니다.

**Comment by yograterol** [comment]
English plz

**Pull request closed without merging**
