### PR TITLE
restore Ethersocial Network(ESN) node

### PR DESCRIPTION
**Pull request by hackmod**
Ethersocial Network(ESN) node accidentally removed by commit 9e17f2154f
and recently, node health check method changed by commit fffa10b44e02

We will add `net_listening` api method asap.

additionally, missing ledger support for ESN added.

cc: @magnalucus, @kimmyeonghun

### CODE REVIEW

**Comment by turbobit** [comment]
``net_listening`` api method added.

**Request example**
curl -H "Content-Type: application/json" -X POST https://api.esn.gonspool.com -d '{"jsonrpc":"2.0","method":"net_listening","params":[],"id":83}'

**Return example**
{"jsonrpc":"2.0","id":"83","result":true}

**Reference**
https://github.com/ethereum/wiki/wiki/JSON-RPC#net_listening

**Comment by hackmod** [comment]
@chainkoreauser == airking. do not feed the real scam developer

**Comment by ghost** [comment]
I am not airking @hackmod , I am a scam victim from you guys, ESN and ETSC!!! :imp::imp::imp:

**Comment by hackmod** [comment]
Ethersocial Network was incubated at the biggest mining community named DDengle(https://www.ddengle.com/esn ) in South Korea.
- main site: https://ethersocial.network
- block explorer: https://ethersocial.net (based on the ETC explorer)
- CMC: https://coinmarketcap.com/currencies/ethersocial/
- exchange: https://www.bit-z.com/exchange/esn_btc
- Trezor supported, MEW supported, MyCrypto supported

all ESN related sites are currently working.

**Comment by ghost** [comment]
Ethersocial is very related with Ethereum Social and it should be considered as a scam whether or not site is alive. It wouldn't be surprisable when ETSC guys come back and scam people, or maybe ESN's dev are the same people with ETSC 😂 

I need compensation with my lost funds with Youbit hack and ESN scam , until then I will keep boycott ESN from open-source community 👿👿👿

**Comment by hackmod** [comment]
See also https://github.com/kvhnuke/etherwallet/pull/1879
image
ghost == airking

image
chainkorea == airking

**Comment by hackmod** [comment]
any reason not merging this PR for 3 months?

**Pull request closed without merging**
