### PR TITLE
Update/array input #57

### PR DESCRIPTION
**Pull request by j-chimienti**
TODO: 

[x] validate fields -> warning added, filtering blank values when estimate Gas / deploy
[x] filter blank values -> not updated in UI

### CODE REVIEW

**Comment by j-chimienti** [comment]
screen shot 2018-03-27 at 11 40 04 am




deployed contract to ropsten network:
https://ropsten.etherscan.io/tx/0xc2e70fab95b0edb02e0a12452658f8271554a8bc8310c669c9e0cfe492021a5d

**Comment by j-chimienti** [comment]
> If the user clicks on the index of a nonexistent array element without changing the value of the element, this element must not be added to the array. (Example: the array of 3 elements is presented. If a user increases the index to 3 then an empty element value will be displayed. It is a non-initialized fourth element of the array. If the user leaves the value of the element with the index 3 unchanged and switches the index to 2, then the array still has 3 elements. If the user has changed the value of the element with index 3 from empty to any valid value of type of the array elemens then the array now has 4 elements and the element with index 3 must be pushed into it.)


Not sure I understand.

when gathering data to  estimate gas  / sign transaction, I am filtering blank values, but isn't reflected in UI atm.

When estimating / signing, should UI array be filtered to remove blank values?



screen shot 2018-03-28 at 9 21 47 am

**Comment by j-chimienti** [comment]
For the arrays, I am am only concerning w/ primitive type arrays, all of the same type. string[], uint[], address[].

I haven't thought about struct[], or if it's possible, I haven't attempted to deploy a contract like that or have seen one.

**Comment by j-chimienti** [comment]
screen shot 2018-03-30 at 10 29 50 am

**Comment by j-chimienti** [comment]
```
pragma solidity ^0.4.18;

pragma experimental ABIEncoderV2;


contract Array {
    
    
    address[] public Addresses;
    
    string[] public Names;
    
    //uint256[] public Numbers;
    
    //bool[] public Booleans;
    
    function Array(address[] owners, string[] names) public {
        
        Addresses = owners;
        
        Names = names;
        
        //Numbers = numbers;
        
       // Booleans = booleans;
        
    }
}

```

I'm testing deploys, I have successfully deployed array in constructor as addresses.

However, when I go make any other type of array, when I estimate gas, I am receiving an error

`"gas required exceeds allowance or always failing transaction"`

I manually entered in gas, and attempted to deploy https://ropsten.etherscan.io/tx/0x542d8901964485b465885375cbe54c1f5fa377c82fa99e01d38c88dbf1ce530c

but unable to check atm due to node resync

**Comment by Dexaran** [comment]
>When estimating / signing, should UI array be filtered to remove blank values?

No.

- If an array element is presented but has empty value then the UI **MUST** throw an error if the element type has non-empty default values. Example: `uint256` can not be empty because the default value of uint256 is 0.

- If an array element is presented but has empty value then the UI **MUST** consider it to be an empty element of an array if the elements type allow empty values. Example: `string` can be empty value.

- CEW should only delete element of array if a user has manually clicked "DELETE" button.

It is necessary to define an array with some empty values in some cases. For example array of strings:

[0] "Alice"
[1] "Bob"
[2} ""
[3] ""
[4] "Dex"
[5] ""
[6] "Some of us are anonymous"

**Comment by Dexaran** [comment]
>but unable to check atm due to node resync

I will recommend that you use a remote node and block explorers. For example it is really easy to test contracts on Rinkeby with rinkeby-infura node and Etherscan explorer. http://rinkeby.etherscan.io/

It will be a big challenge for you to sync all nodes for all networks if we need to test internetwork services.

**Comment by Dexaran** [comment]
It is necessary to implement the array type support for normal function executions (at `contracts` tab).

https://ethereumproject.github.io/etherwallet/#contracts

Here is an example contract:

```js
pragma solidity ^0.4.15;

contract ArrayTest {
    
    uint256[] public uints;
    address[] public addresses;
    
    function getBalance(address _addr) constant returns(uint256)
    {
        return _addr.balance;
    }
    
    function setUints(uint256[] _uints)
    {
        for (uint256 i; i<_uints.length; i++)
        {
            uints[i] = _uints[i];
        }
    }
}
``` 

The described functionality should work with `setUints` function.

**Comment by Dexaran** [comment]
Here is my test contract: https://github.com/Dexaran/TestContractArrays/

I'm trying to deploy it but the transaction fails: https://rinkeby.etherscan.io/address/0x875fb75bcfe8a81b0660d851da1f9eac75c43781

[Transaction link](https://rinkeby.etherscan.io/tx/0xe2b083c89ab4e4da8da0527bde3609de14c84d277e5bd4fa9278796a099b40ae).

I'm deploying contract with following parameters:

deploy_err

**Comment by j-chimienti** [comment]
I've had trouble with the test contract as well.  https://github.com/Dexaran/TestContractArrays/


I've had success with a modified version of the contract and can set values w/ new UI.


https://ropsten.etherscan.io/address/0x0db9d2dee092097a6630a70d3f8e492811021503

```

pragma solidity ^0.4.15;

contract ArrayTest {
    
    uint256[] public uints;
    
    address[] public addresses;
    
    function getBalance(address _addr) constant returns(uint256)
    {
        return _addr.balance;
    }
    
     function setAddrs(address[] _addrs)
    {
        addresses = _addrs;
    }
    
      function setUints(uint256[] _uints)
    {
        for (uint256 i; i<_uints.length; i++)
        {
            uints.push(_uints[i]);
        }
    }
    
   
}

```

Also, I've seen contracts w/ arrays are tough to implement.

Starting w/ example from https://solidity.readthedocs.io/en/latest/solidity-by-example.html

```

**working:**
function Ballot(bytes32[] proposalNames) public {

function Ballot(bytes32[] proposalNames, addresses[] addrs) public {

**non working:**

function Ballot(bytes32[] proposalNames, string[] strings_) public {

```

**Comment by Dexaran** [comment]
@j-chimienti it seems that the problem still stands for me. I can't deploy the `TestArray` contract even now.

http://gastracker.io/tx/0x7bc0319073ac8db68851b75d4e4e54c304779b11011d2d3288f7655cdf4bd443

**Comment by Dexaran** [comment]
I like the visual implementation. It seems that it is intuitively-clear enough.

**Comment by j-chimienti** [comment]
> it seems that the problem still stands for me. I can't deploy the TestArray contract even now.

kk, ill look into right now. I was going to move onto changenow swap

**Pull request merged**
