### PR TITLE
background node variable

### PR DESCRIPTION
**Pull request by j-chimienti**

### CODE REVIEW

**Comment by j-chimienti** [comment]
I am picking random node to default w/.  And chooses randomly b/w the remaining 2 background nodes, when switching

We can set default, or weighting if necessary.

**Comment by Dexaran** [comment]
We need a dropdown menu to allow for changing the background node. 
- background node is one of the ETC nodes

background_node

**Comment by j-chimienti** [comment]
added dropdown

**Comment by j-chimienti** [comment]
screen shot 2018-03-23 at 2 58 41 pm

**Pull request merged**
