### PR TITLE
disable EIP-155 for PIRL just as was done for CLO

### PR DESCRIPTION
**Pull request by mkrufky**
As discussed in #137 , there is an issue signing tx w/ EIP-155 support on the PIRL network just as the CLO network.

This fixes the "invalid sender" error when trying to sign a tx on the PIRL network when using a HW wallet.

Also, change the default HD Derivation path for PIRL to its own unique path of "m/44'/164'/0'/0"

### CODE REVIEW

**Comment by hackmod** [comment]
See also
- https://github.com/kvhnuke/etherwallet/pull/1921
- https://github.com/LedgerHQ/ledgerjs/issues/168

**Comment by mkrufky** [comment]
@akx20000x  I saw your (deleted) comment and (removed) approval.  I understand if we have to wait before merging the Pirl specifics, so I'll send the "fix broken layout" patch in a separate PR.

In the meantime, please let me know what holds up this pull request.   Is it because of the disabled EIP-155?  Thanks in advance

**Comment by mkrufky** [comment]
The "fix broken layout" patch has been removed from this PR and now exists alone in its own PR, here:  https://github.com/EthereumCommonwealth/etherwallet/pull/197

**Comment by hackmod** [comment]
akx20000x is not actually ETC dev team at all.

**Comment by ghost** [comment]
@mkrufky Hello sorry for my comment removal,

There was a censorship from github so I am moving my work to gitlab, and I would like to thank you about your PR for fixing bugs from @hackmod PR.

I've seen the bug from https://github.com/EthereumCommonwealth/etherwallet/pull/158 however I didn't tell dexaran before merging it, anyways I am ACK for this pr as it already submitted for CLO.

**Comment by mkrufky** [comment]
I am closing this pull request, as Pirl now fully supports EIP-155 correctly in the new Pirl Ledger Nano S app.  It requires a v recalculation in the javascript.  I have it working and tested, but needs some cleanup.  I'll open a new PR shortly.

**Pull request closed without merging**
